a = input("Digite um valor para as operações: ")
b = input("Digite um segundo valor para as operações: ")
soma = int(a) + int(b)
subtrair = int(a) - int(b)
multiplicar = int(a) * int(b)
dividir = float(a) / float(b)
exponente = int(a) ** int(b)
restoDivisao = float(a) % float(b)

print("O valor somado é: " + str(soma))
print("O valor subtraído é: " + str(subtrair))
print("O valor multiplicado é: " + str(multiplicar))
print("O valor dividido é: " + str(dividir))
print("O valor exponentizado pelo outro é: " + str(exponente))
print("O resto da divisão é: " + str(restoDivisao))
