valorIphone = int(2980); valorSamsung = int(2540); valorTablet = int(1950); valorPs5 = int(2100); valorNotebook = int(2350)

quantIphone = int(input("Digite a quantidade de iPhone, caso nao queira digite 0: "))
quantSamsung = int(input("Digite a quantidade de Samsung, caso nao queira digite 0: "))
quantTablet = int(input("Digite a quantidade de Tablet, caso nao queira digite 0: "))
quantPs5 = int(input("Digite a quantidade de Ps5, caso nao queira digite 0: "))
quantNotebook = int(input("Digite a quantidade de Notebook, caso nao queira digite 0: "))
print("")
print("O valor somado de cada produto é:")
print("iPhone: ", valorIphone * quantIphone)
print("Samsung: ", valorSamsung * quantSamsung)
print("Tablet: ", valorTablet * quantTablet)
print("Ps5: ", valorPs5 * quantPs5)
print("Notebook: ", valorNotebook * quantNotebook)
print("")
print("Parcelado em 3x: ")
print("iPhone: ", (valorIphone * quantIphone) / 3)
print("Samsung: ", (valorSamsung * quantSamsung) / 3)
print("Tablet: ", (valorTablet * quantTablet) / 3)
print("Ps5: ", (valorPs5 * quantPs5) / 3)
print("Notebook: ", (valorNotebook * quantNotebook) / 3)
print("")
print("Parcelado em 6x com juros de 5%: ")
print("iPhone: ", (valorIphone * quantIphone) * 1.05 / 6)
print("Samsung: ", (valorSamsung * quantSamsung) * 1.05 / 6)
print("Tablet: ", (valorTablet * quantTablet) * 1.05 / 6)
print("Ps5: ", (valorPs5 * quantPs5) * 1.05 / 6)
print("Notebook: ", (valorNotebook * quantNotebook) * 1.05 / 6)
print("")
print("O valor a vista com 10% de desconto: ")
print("iPhone: ", (valorIphone * quantIphone) - (valorIphone * quantIphone * 0.1))
print("Samsung: ", (valorSamsung * quantSamsung) - (valorSamsung * quantSamsung * 0.1))
print("Tablet: ", (valorTablet * quantTablet) - (valorTablet * quantTablet * 0.1))
print("Ps5: ", (valorPs5 * quantPs5) - (valorPs5 * quantPs5 * 0.1))
print("Notebook: ", (valorNotebook * quantNotebook) - (valorNotebook * quantNotebook * 0.1))

#FIM